pipeline {
    agent any

    parameters {
        string(defaultValue: "TEST", description: "Which environment to deploy in?", name: "deployEnv")
    }

    stages {
        stage("Demo") {
            steps {
                echo "The app will be deployed in ${params.deployEnv}"
            }
        }
    }
}