pipeline {
    agent any

    environment {
        boolean isOk = true;
        String hello = "Hello folks!"
        Long lNumber = 1000
        Double dNumber = 0.123
    }

    parameters {
        string(defaultValue: "Deployment name", description: "Give the name to the deployment:", name: "depName")
        booleanParam(defaultValue: false, description: "Auto start after deployment finished?", name: "autoStart")
        choice(choices: ["US-NewYork", "EU-London", "ASIA-Tokyo"], description: "Select the time zone to deploy:", name: "timeZone")
    }

    stages {
        stage("Description") {
            steps {
                echo "Deployment ${params.depName}"
                echo "auto start set to: ${params.autoStart}"
                echo "Time zone: ${timeZone}"
            }
        }
        stage("Variables demo") {
            steps {
                echo "is it ok? ${isOK ? 'yes': 'no'}"
                echo "${hello}"
                echo "Long equals to ${lNumber}"
                echo "Double equals to ${dNumber}"
            }
        }
        stage("Compile") {
            steps {
                sh "./gradlew clean build"
            }
        }
        stage("Test") {
            steps {
                sh "./gradlew test"
            }
        }
        stage("Run") {
            steps {
                sh "./gradlew run"
            }
        }
    }
}