pipeline {
    agent any

    parameters {
        string(defaultValue: "Deployment name", description: "Give the name to the deployment:", name: "depName")
        booleanParam(defaultValue: false, description: "Auto start after deployment finished?", name: "autoStart")
        choice(choices: ["US-NewYork", "EU-London", "ASIA-Tokyo"], description: "Select the time zone to deploy:", name: "timeZone")
    }

    stages {
        stage("Description") {
            steps {
                echo "Deployment ${params.depName}; auto start set to: ${params.autoStart}; Time zone: ${timeZone}"
            }
        }
        stage("Clone") {
            steps {
                sh "git clone"
            }
        }
        stage("Compile") {
            steps {
                sh "./gradlew clean build"
            }
        }
        stage("Test") {
            steps {
                sh "./gradlew test"
            }
        }
        stage("Run") {
            steps {
                sh "./gradlew run"
            }
        }
    }
}